// Fixed toolbar for the Discussions TextEditor.
// Mirrors frappe-ui's default fixed menu (TextEditorFixedMenu.vue) but omits
// the "Iframe" button (labelled "Embed") so learners can't embed iframes in
// batch discussions.
export const discussionFixedMenu = [
	'Paragraph',
	['Heading 1', 'Heading 2', 'Heading 3', 'Heading 4', 'Heading 5', 'Heading 6'],
	'Separator',
	'Bold',
	'Italic',
	'Strikethrough',
	'Link',
	'FontColor',
	'Separator',
	'Bullet List',
	'Numbered List',
	'Task List',
	'Separator',
	'Align Left',
	'Align Center',
	'Align Right',
	'Separator',
	'Image',
	'Video',
	'Blockquote',
	'Code',
	'Separator',
	'Horizontal Rule',
	[
		'InsertTable',
		'AddColumnBefore',
		'AddColumnAfter',
		'DeleteColumn',
		'AddRowBefore',
		'AddRowAfter',
		'DeleteRow',
		'MergeCells',
		'SplitCell',
		'ToggleHeaderColumn',
		'ToggleHeaderRow',
		'ToggleHeaderCell',
		'DeleteTable',
	],
	'Separator',
	'TableOfContents',
	'Separator',
	'Undo',
	'Redo',
]
